org: akaviles024
app: node-lambda-2
service: node-lambda-2
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId: ${cf:shared-gateway-dev.apiGatewayRestApiId}
    restApiRootResourceId: !Ref rApiGatewayAdmins
functions:
  admins:
    handler: index.handler
    events:
      - http:
          path: !Ref rApiGateWayEmptyPath
          method: get

resources:
  - Resources:
      rApiGatewayAdmins:
        Type: AWS::ApiGateway::Resource
        Properties:
          ParentId: ${cf:shared-gateway-dev.apiGatewayRestApiRootResourceId}
          PathPart: admins
          RestApiId: ${cf:shared-gateway-dev.apiGatewayRestApiId}
      rApiGateWayEmptyPath:
        Type: AWS::ApiGateway::Resource
        Properties:
          Path: users
  - Outputs:
      oApiGatewayAdminsId:
        Value:
          Ref: rApiGatewayAdmins
        Export:
          Name: admins-apigateway
      oApiGatewayAdminUsersId:
        Value:
          Ref: rApiGateWayEmptyPath
        Export:
          Name: users-empty-path
